// Users
export const getUsers = 'get-users'
export const getUser = 'get-user'
export const usersError = 'users-error'
export const deleteUser = 'delete-user'
export const deleteAllUsers = 'delete-all-users'
export const addUser = 'add-user'
export const usersMessage = 'users-message'
export const usersWarning = 'users-warning'
export const usersFormError = 'users-form-error'
export const userLogIn = 'user-log-in'
export const userLogOut = 'user-log-out'
export const showAlert = 'show-alert'
export const getContactMessages = 'get-contact-messages'
export const deleteContactMessage = 'delete-contact-message'
export const getImages = 'get-gallery-images'

// Cbt Users
export const getCbtUsers = 'get-cbt-users'
export const cbtUserLogIn = 'cbt-user-login'
export const cbtUserLogOut = 'cbt-user-logout'
export const addCbtUser = 'add-cbt-user'
export const getCbtUser = 'get-cbt-user'
export const deleteCbtUser = 'delete-cbt-user'
export const deleteAllCbtUsers = 'delete-all-cbt-users'
export const createExam = 'create-exam'
export const updateExam = 'update-exam'
export const findCbtUser = 'find-cbt-user'
export const getCbtExams = 'get-cbt-exams'
export const examCategory = 'exam-category'
export const examAnswered = 'exam-answered'
export const addQuestion = 'add-question'
export const editQuestion = 'edit-question'
export const getCbtQuestions = 'get-cbt-question' 
export const getScores = 'get-scores' 

// News
export const getCryptos = 'get-cryptos'
export const getCrypto = 'get-crypto'
export const getCryptoNews = 'get-crypto-news'
export const getBingNews = 'get-bing-news'
export const getCryptoHistory = 'get-crypto-history'
export const getPosts = 'get-posts'
