// Users
export const getUsers = 'get-users'
export const getUser = 'get-user'
export const usersError = 'users-error'
export const deleteUser = 'delete-user'
export const deleteAllUsers = 'delete-all-users'
export const addUser = 'add-user'
export const updateUser = 'update-user'
export const usersMessage = 'users-message'
export const userLogIn = 'user-log-in'
export const userLogOut = 'user-log-out'

// Cbt Users
export const getCbtUsers = 'get-cbt-users'
export const cbtUserLogIn = 'cbt-user-login'
export const cbtUserLogOut = 'cbt-user-logout'
export const updateCbtUser = 'update-cbt-user'
export const registerCbtUser = 'register-cbt-user'
export const addCbtUser = 'add-cbt-user'
export const getCbtUser = 'get-cbt-user'
export const deleteCbtUser = 'delete-cbt-user'
export const deleteAllCbtUsers = 'delete-all-cbt-users'